package app.androidhive.info.realm.model;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class Book extends RealmObject {

    @PrimaryKey
    private long id;

    private String nombre;

    private String genero;

    private String raza;

    private String imageUrl;

    private String proposito;
    private String fecha_nacimiento;
    private double peso_al_nacer;
    private double peso_al_desteste;

    //Datos del padre
    private String nombre_padre;
    private String codigo_padre;
    private String raza_padre;

    //Datos de la madre

    private String nombre_madre;
    private String codigo_madre;
    private String raza_madre;

    private String alimentacion;
    private String cantidadLibras, numeroOrdenos, precioLitro, numerodeCrias;


    // Standard getters & setters generated by your IDE…


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getRaza() {
        return raza;
    }

    public void setRaza(String raza) {
        this.raza = raza;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getProposito() {
        return proposito;
    }

    public void setProposito(String proposito) {
        this.proposito = proposito;
    }

    public String getFecha_nacimiento() {
        return fecha_nacimiento;
    }

    public void setFecha_nacimiento(String fecha_nacimiento) {
        this.fecha_nacimiento = fecha_nacimiento;
    }

    public double getPeso_al_nacer() {
        return peso_al_nacer;
    }

    public void setPeso_al_nacer(double peso_al_nacer) {
        this.peso_al_nacer = peso_al_nacer;
    }

    public double getPeso_al_desteste() {
        return peso_al_desteste;
    }

    public void setPeso_al_desteste(double peso_al_desteste) {
        this.peso_al_desteste = peso_al_desteste;
    }

    public String getNombre_padre() {
        return nombre_padre;
    }

    public void setNombre_padre(String nombre_padre) {
        this.nombre_padre = nombre_padre;
    }

    public String getCodigo_padre() {
        return codigo_padre;
    }

    public void setCodigo_padre(String codigo_padre) {
        this.codigo_padre = codigo_padre;
    }

    public String getRaza_padre() {
        return raza_padre;
    }

    public void setRaza_padre(String raza_padre) {
        this.raza_padre = raza_padre;
    }

    public String getNombre_madre() {
        return nombre_madre;
    }

    public void setNombre_madre(String nombre_madre) {
        this.nombre_madre = nombre_madre;
    }

    public String getCodigo_madre() {
        return codigo_madre;
    }

    public void setCodigo_madre(String codigo_madre) {
        this.codigo_madre = codigo_madre;
    }

    public String getRaza_madre() {
        return raza_madre;
    }

    public void setRaza_madre(String raza_madre) {
        this.raza_madre = raza_madre;
    }

    public String getAlimentacion() {
        return alimentacion;
    }

    public void setAlimentacion(String alimentacion) {
        this.alimentacion = alimentacion;
    }

    public String getCantidadLibras() {
        return cantidadLibras;
    }

    public void setCantidadLibras(String cantidadLibras) {
        this.cantidadLibras = cantidadLibras;
    }

    public String getNumeroOrdenos() {
        return numeroOrdenos;
    }

    public void setNumeroOrdenos(String numeroOrdenos) {
        this.numeroOrdenos = numeroOrdenos;
    }

    public String getPrecioLitro() {
        return precioLitro;
    }

    public void setPrecioLitro(String precioLitro) {
        this.precioLitro = precioLitro;
    }

    public String getNumerodeCrias() {
        return numerodeCrias;
    }

    public void setNumerodeCrias(String numerodeCrias) {
        this.numerodeCrias = numerodeCrias;
    }
}

